// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kadsdqnpxzgdxnnrdzra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZHNkcW5weHpnZHhubnJkenJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzM3MDksImV4cCI6MjA2NDYwOTcwOX0.hBxdxwJOljZ4peYkYxN4Va_BcHqmqay7kQP7ijqio7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});